// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.0
// source: microtiezi/proto/tiezi.proto

package microtieiz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *gorm.Model
// 	Userid     string `json:"userid" form:"userid"`
// 	Content    string `json:"content" form:"content"`
// 	Title      string `json:"title" form:"title"`
// 	Photourl   string `json:"photourl" form:"photourl"`
// 	Dianzanshu int    `json:"dianzanshu" form:"dianzanshu"`
type Tiezigetrequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Userid int64 `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *Tiezigetrequest) Reset() {
	*x = Tiezigetrequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microtiezi_proto_tiezi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tiezigetrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tiezigetrequest) ProtoMessage() {}

func (x *Tiezigetrequest) ProtoReflect() protoreflect.Message {
	mi := &file_microtiezi_proto_tiezi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tiezigetrequest.ProtoReflect.Descriptor instead.
func (*Tiezigetrequest) Descriptor() ([]byte, []int) {
	return file_microtiezi_proto_tiezi_proto_rawDescGZIP(), []int{0}
}

func (x *Tiezigetrequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tiezigetrequest) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type Tiezigetresponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Userid     int64  `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Title      string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Photourl   string `protobuf:"bytes,5,opt,name=photourl,proto3" json:"photourl,omitempty"`
	Dianzanshu int64  `protobuf:"varint,6,opt,name=dianzanshu,proto3" json:"dianzanshu,omitempty"`
}

func (x *Tiezigetresponse) Reset() {
	*x = Tiezigetresponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microtiezi_proto_tiezi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tiezigetresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tiezigetresponse) ProtoMessage() {}

func (x *Tiezigetresponse) ProtoReflect() protoreflect.Message {
	mi := &file_microtiezi_proto_tiezi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tiezigetresponse.ProtoReflect.Descriptor instead.
func (*Tiezigetresponse) Descriptor() ([]byte, []int) {
	return file_microtiezi_proto_tiezi_proto_rawDescGZIP(), []int{1}
}

func (x *Tiezigetresponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tiezigetresponse) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *Tiezigetresponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Tiezigetresponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Tiezigetresponse) GetPhotourl() string {
	if x != nil {
		return x.Photourl
	}
	return ""
}

func (x *Tiezigetresponse) GetDianzanshu() int64 {
	if x != nil {
		return x.Dianzanshu
	}
	return 0
}

type Createtieziquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid     int64  `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Title      string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Photourl   string `protobuf:"bytes,5,opt,name=photourl,proto3" json:"photourl,omitempty"`
	Dianzanshu int64  `protobuf:"varint,6,opt,name=dianzanshu,proto3" json:"dianzanshu,omitempty"`
}

func (x *Createtieziquest) Reset() {
	*x = Createtieziquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microtiezi_proto_tiezi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Createtieziquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Createtieziquest) ProtoMessage() {}

func (x *Createtieziquest) ProtoReflect() protoreflect.Message {
	mi := &file_microtiezi_proto_tiezi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Createtieziquest.ProtoReflect.Descriptor instead.
func (*Createtieziquest) Descriptor() ([]byte, []int) {
	return file_microtiezi_proto_tiezi_proto_rawDescGZIP(), []int{2}
}

func (x *Createtieziquest) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *Createtieziquest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Createtieziquest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Createtieziquest) GetPhotourl() string {
	if x != nil {
		return x.Photourl
	}
	return ""
}

func (x *Createtieziquest) GetDianzanshu() int64 {
	if x != nil {
		return x.Dianzanshu
	}
	return 0
}

type CreatetieziResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Flag int64 `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"` //是否成功
}

func (x *CreatetieziResponse) Reset() {
	*x = CreatetieziResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microtiezi_proto_tiezi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatetieziResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatetieziResponse) ProtoMessage() {}

func (x *CreatetieziResponse) ProtoReflect() protoreflect.Message {
	mi := &file_microtiezi_proto_tiezi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatetieziResponse.ProtoReflect.Descriptor instead.
func (*CreatetieziResponse) Descriptor() ([]byte, []int) {
	return file_microtiezi_proto_tiezi_proto_rawDescGZIP(), []int{3}
}

func (x *CreatetieziResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreatetieziResponse) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type Tiezilistrequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pageoffset int64 `protobuf:"varint,1,opt,name=pageoffset,proto3" json:"pageoffset,omitempty"`
}

func (x *Tiezilistrequest) Reset() {
	*x = Tiezilistrequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microtiezi_proto_tiezi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tiezilistrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tiezilistrequest) ProtoMessage() {}

func (x *Tiezilistrequest) ProtoReflect() protoreflect.Message {
	mi := &file_microtiezi_proto_tiezi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tiezilistrequest.ProtoReflect.Descriptor instead.
func (*Tiezilistrequest) Descriptor() ([]byte, []int) {
	return file_microtiezi_proto_tiezi_proto_rawDescGZIP(), []int{4}
}

func (x *Tiezilistrequest) GetPageoffset() int64 {
	if x != nil {
		return x.Pageoffset
	}
	return 0
}

type TiezilistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*TiezilistResponse_List `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *TiezilistResponse) Reset() {
	*x = TiezilistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microtiezi_proto_tiezi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TiezilistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TiezilistResponse) ProtoMessage() {}

func (x *TiezilistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_microtiezi_proto_tiezi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TiezilistResponse.ProtoReflect.Descriptor instead.
func (*TiezilistResponse) Descriptor() ([]byte, []int) {
	return file_microtiezi_proto_tiezi_proto_rawDescGZIP(), []int{5}
}

func (x *TiezilistResponse) GetList() []*TiezilistResponse_List {
	if x != nil {
		return x.List
	}
	return nil
}

// *gorm.Model
// 	Postid  string `json:"postid" form:"postid" binding:"required"`
// 	Time    string `json:"time" form:"time"`
// 	Uid     int    `json:"uid" form:"uid"`
// 	Content string `json:"content" form:"content"`
type Createtiezipinglunquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Postid  int64  `protobuf:"varint,2,opt,name=postid,proto3" json:"postid,omitempty"`
	Uid     int64  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Createtiezipinglunquest) Reset() {
	*x = Createtiezipinglunquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microtiezi_proto_tiezi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Createtiezipinglunquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Createtiezipinglunquest) ProtoMessage() {}

func (x *Createtiezipinglunquest) ProtoReflect() protoreflect.Message {
	mi := &file_microtiezi_proto_tiezi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Createtiezipinglunquest.ProtoReflect.Descriptor instead.
func (*Createtiezipinglunquest) Descriptor() ([]byte, []int) {
	return file_microtiezi_proto_tiezi_proto_rawDescGZIP(), []int{6}
}

func (x *Createtiezipinglunquest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Createtiezipinglunquest) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

func (x *Createtiezipinglunquest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CreatetiezipinglunResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag int64 `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"` //是否成功
}

func (x *CreatetiezipinglunResponse) Reset() {
	*x = CreatetiezipinglunResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microtiezi_proto_tiezi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatetiezipinglunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatetiezipinglunResponse) ProtoMessage() {}

func (x *CreatetiezipinglunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_microtiezi_proto_tiezi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatetiezipinglunResponse.ProtoReflect.Descriptor instead.
func (*CreatetiezipinglunResponse) Descriptor() ([]byte, []int) {
	return file_microtiezi_proto_tiezi_proto_rawDescGZIP(), []int{7}
}

func (x *CreatetiezipinglunResponse) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type Tiezipinglunlistrequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page   int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Postid int64 `protobuf:"varint,2,opt,name=postid,proto3" json:"postid,omitempty"`
}

func (x *Tiezipinglunlistrequest) Reset() {
	*x = Tiezipinglunlistrequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microtiezi_proto_tiezi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tiezipinglunlistrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tiezipinglunlistrequest) ProtoMessage() {}

func (x *Tiezipinglunlistrequest) ProtoReflect() protoreflect.Message {
	mi := &file_microtiezi_proto_tiezi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tiezipinglunlistrequest.ProtoReflect.Descriptor instead.
func (*Tiezipinglunlistrequest) Descriptor() ([]byte, []int) {
	return file_microtiezi_proto_tiezi_proto_rawDescGZIP(), []int{8}
}

func (x *Tiezipinglunlistrequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Tiezipinglunlistrequest) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

type TiezipinglunlistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*TiezipinglunlistResponse_List `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *TiezipinglunlistResponse) Reset() {
	*x = TiezipinglunlistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microtiezi_proto_tiezi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TiezipinglunlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TiezipinglunlistResponse) ProtoMessage() {}

func (x *TiezipinglunlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_microtiezi_proto_tiezi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TiezipinglunlistResponse.ProtoReflect.Descriptor instead.
func (*TiezipinglunlistResponse) Descriptor() ([]byte, []int) {
	return file_microtiezi_proto_tiezi_proto_rawDescGZIP(), []int{9}
}

func (x *TiezipinglunlistResponse) GetList() []*TiezipinglunlistResponse_List {
	if x != nil {
		return x.List
	}
	return nil
}

type TiezilistResponse_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Userid     int64  `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Title      string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Photourl   string `protobuf:"bytes,5,opt,name=photourl,proto3" json:"photourl,omitempty"`
	Dianzanshu int64  `protobuf:"varint,6,opt,name=dianzanshu,proto3" json:"dianzanshu,omitempty"`
}

func (x *TiezilistResponse_List) Reset() {
	*x = TiezilistResponse_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microtiezi_proto_tiezi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TiezilistResponse_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TiezilistResponse_List) ProtoMessage() {}

func (x *TiezilistResponse_List) ProtoReflect() protoreflect.Message {
	mi := &file_microtiezi_proto_tiezi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TiezilistResponse_List.ProtoReflect.Descriptor instead.
func (*TiezilistResponse_List) Descriptor() ([]byte, []int) {
	return file_microtiezi_proto_tiezi_proto_rawDescGZIP(), []int{5, 0}
}

func (x *TiezilistResponse_List) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TiezilistResponse_List) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *TiezilistResponse_List) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TiezilistResponse_List) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TiezilistResponse_List) GetPhotourl() string {
	if x != nil {
		return x.Photourl
	}
	return ""
}

func (x *TiezilistResponse_List) GetDianzanshu() int64 {
	if x != nil {
		return x.Dianzanshu
	}
	return 0
}

type TiezipinglunlistResponse_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Postid  int64  `protobuf:"varint,2,opt,name=postid,proto3" json:"postid,omitempty"`
	Uid     int64  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Id      int64  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TiezipinglunlistResponse_List) Reset() {
	*x = TiezipinglunlistResponse_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microtiezi_proto_tiezi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TiezipinglunlistResponse_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TiezipinglunlistResponse_List) ProtoMessage() {}

func (x *TiezipinglunlistResponse_List) ProtoReflect() protoreflect.Message {
	mi := &file_microtiezi_proto_tiezi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TiezipinglunlistResponse_List.ProtoReflect.Descriptor instead.
func (*TiezipinglunlistResponse_List) Descriptor() ([]byte, []int) {
	return file_microtiezi_proto_tiezi_proto_rawDescGZIP(), []int{9, 0}
}

func (x *TiezipinglunlistResponse_List) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TiezipinglunlistResponse_List) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

func (x *TiezipinglunlistResponse_List) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *TiezipinglunlistResponse_List) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_microtiezi_proto_tiezi_proto protoreflect.FileDescriptor

var file_microtiezi_proto_tiezi_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x22, 0x39, 0x0a, 0x0f, 0x54, 0x69,
	0x65, 0x7a, 0x69, 0x67, 0x65, 0x74, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0xa6, 0x01, 0x0a, 0x10, 0x54, 0x69, 0x65, 0x7a, 0x69, 0x67,
	0x65, 0x74, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x73, 0x68, 0x75, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x73, 0x68, 0x75, 0x22, 0x96,
	0x01, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x61, 0x6e, 0x7a,
	0x61, 0x6e, 0x73, 0x68, 0x75, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x69, 0x61,
	0x6e, 0x7a, 0x61, 0x6e, 0x73, 0x68, 0x75, 0x22, 0x39, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x22, 0x32, 0x0a, 0x10, 0x54, 0x69, 0x65, 0x7a, 0x69, 0x6c, 0x69, 0x73, 0x74, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0xe8, 0x01, 0x0a, 0x11, 0x54, 0x69, 0x65, 0x7a, 0x69,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x2e, 0x54, 0x69, 0x65, 0x7a, 0x69, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x1a, 0x9a, 0x01, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72,
	0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x73, 0x68, 0x75, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x73, 0x68,
	0x75, 0x22, 0x5d, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x69, 0x65, 0x7a, 0x69,
	0x70, 0x69, 0x6e, 0x67, 0x6c, 0x75, 0x6e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x22, 0x30, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x70,
	0x69, 0x6e, 0x67, 0x6c, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x22, 0x45, 0x0a, 0x17, 0x54, 0x69, 0x65, 0x7a, 0x69, 0x70, 0x69, 0x6e, 0x67, 0x6c,
	0x75, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x22, 0xb5, 0x01, 0x0a, 0x18, 0x54, 0x69,
	0x65, 0x7a, 0x69, 0x70, 0x69, 0x6e, 0x67, 0x6c, 0x75, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x74, 0x69, 0x65, 0x7a,
	0x69, 0x2e, 0x54, 0x69, 0x65, 0x7a, 0x69, 0x70, 0x69, 0x6e, 0x67, 0x6c, 0x75, 0x6e, 0x6c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x5a, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x32, 0xa0, 0x03, 0x0a, 0x0c, 0x54, 0x69, 0x65, 0x7a, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x49, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x74, 0x69, 0x65, 0x7a, 0x69, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x69,
	0x65, 0x7a, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a,
	0x03, 0x47, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x74, 0x69, 0x65, 0x7a,
	0x69, 0x2e, 0x54, 0x69, 0x65, 0x7a, 0x69, 0x67, 0x65, 0x74, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x2e, 0x54,
	0x69, 0x65, 0x7a, 0x69, 0x67, 0x65, 0x74, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x45, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x2e, 0x54, 0x69, 0x65, 0x7a, 0x69, 0x6c, 0x69, 0x73, 0x74,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x74,
	0x69, 0x65, 0x7a, 0x69, 0x2e, 0x54, 0x69, 0x65, 0x7a, 0x69, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x70, 0x69, 0x6e, 0x67, 0x6c, 0x75, 0x6e, 0x12, 0x23, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x69, 0x65,
	0x7a, 0x69, 0x70, 0x69, 0x6e, 0x67, 0x6c, 0x75, 0x6e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x70, 0x69, 0x6e, 0x67, 0x6c, 0x75, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74,
	0x70, 0x69, 0x6e, 0x67, 0x6c, 0x75, 0x6e, 0x12, 0x23, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x74,
	0x69, 0x65, 0x7a, 0x69, 0x2e, 0x54, 0x69, 0x65, 0x7a, 0x69, 0x70, 0x69, 0x6e, 0x67, 0x6c, 0x75,
	0x6e, 0x6c, 0x69, 0x73, 0x74, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x74, 0x69, 0x65, 0x7a, 0x69, 0x2e, 0x54, 0x69, 0x65, 0x7a, 0x69, 0x70,
	0x69, 0x6e, 0x67, 0x6c, 0x75, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x74, 0x69, 0x65, 0x69, 0x7a, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_microtiezi_proto_tiezi_proto_rawDescOnce sync.Once
	file_microtiezi_proto_tiezi_proto_rawDescData = file_microtiezi_proto_tiezi_proto_rawDesc
)

func file_microtiezi_proto_tiezi_proto_rawDescGZIP() []byte {
	file_microtiezi_proto_tiezi_proto_rawDescOnce.Do(func() {
		file_microtiezi_proto_tiezi_proto_rawDescData = protoimpl.X.CompressGZIP(file_microtiezi_proto_tiezi_proto_rawDescData)
	})
	return file_microtiezi_proto_tiezi_proto_rawDescData
}

var file_microtiezi_proto_tiezi_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_microtiezi_proto_tiezi_proto_goTypes = []interface{}{
	(*Tiezigetrequest)(nil),               // 0: microtiezi.Tiezigetrequest
	(*Tiezigetresponse)(nil),              // 1: microtiezi.Tiezigetresponse
	(*Createtieziquest)(nil),              // 2: microtiezi.Createtieziquest
	(*CreatetieziResponse)(nil),           // 3: microtiezi.CreatetieziResponse
	(*Tiezilistrequest)(nil),              // 4: microtiezi.Tiezilistrequest
	(*TiezilistResponse)(nil),             // 5: microtiezi.TiezilistResponse
	(*Createtiezipinglunquest)(nil),       // 6: microtiezi.Createtiezipinglunquest
	(*CreatetiezipinglunResponse)(nil),    // 7: microtiezi.CreatetiezipinglunResponse
	(*Tiezipinglunlistrequest)(nil),       // 8: microtiezi.Tiezipinglunlistrequest
	(*TiezipinglunlistResponse)(nil),      // 9: microtiezi.TiezipinglunlistResponse
	(*TiezilistResponse_List)(nil),        // 10: microtiezi.TiezilistResponse.List
	(*TiezipinglunlistResponse_List)(nil), // 11: microtiezi.TiezipinglunlistResponse.List
}
var file_microtiezi_proto_tiezi_proto_depIdxs = []int32{
	10, // 0: microtiezi.TiezilistResponse.list:type_name -> microtiezi.TiezilistResponse.List
	11, // 1: microtiezi.TiezipinglunlistResponse.list:type_name -> microtiezi.TiezipinglunlistResponse.List
	2,  // 2: microtiezi.TieziService.Create:input_type -> microtiezi.Createtieziquest
	0,  // 3: microtiezi.TieziService.Get:input_type -> microtiezi.Tiezigetrequest
	4,  // 4: microtiezi.TieziService.List:input_type -> microtiezi.Tiezilistrequest
	6,  // 5: microtiezi.TieziService.Createpinglun:input_type -> microtiezi.Createtiezipinglunquest
	8,  // 6: microtiezi.TieziService.Listpinglun:input_type -> microtiezi.Tiezipinglunlistrequest
	3,  // 7: microtiezi.TieziService.Create:output_type -> microtiezi.CreatetieziResponse
	1,  // 8: microtiezi.TieziService.Get:output_type -> microtiezi.Tiezigetresponse
	5,  // 9: microtiezi.TieziService.List:output_type -> microtiezi.TiezilistResponse
	7,  // 10: microtiezi.TieziService.Createpinglun:output_type -> microtiezi.CreatetiezipinglunResponse
	9,  // 11: microtiezi.TieziService.Listpinglun:output_type -> microtiezi.TiezipinglunlistResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_microtiezi_proto_tiezi_proto_init() }
func file_microtiezi_proto_tiezi_proto_init() {
	if File_microtiezi_proto_tiezi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_microtiezi_proto_tiezi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tiezigetrequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microtiezi_proto_tiezi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tiezigetresponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microtiezi_proto_tiezi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Createtieziquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microtiezi_proto_tiezi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatetieziResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microtiezi_proto_tiezi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tiezilistrequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microtiezi_proto_tiezi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TiezilistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microtiezi_proto_tiezi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Createtiezipinglunquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microtiezi_proto_tiezi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatetiezipinglunResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microtiezi_proto_tiezi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tiezipinglunlistrequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microtiezi_proto_tiezi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TiezipinglunlistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microtiezi_proto_tiezi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TiezilistResponse_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microtiezi_proto_tiezi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TiezipinglunlistResponse_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_microtiezi_proto_tiezi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_microtiezi_proto_tiezi_proto_goTypes,
		DependencyIndexes: file_microtiezi_proto_tiezi_proto_depIdxs,
		MessageInfos:      file_microtiezi_proto_tiezi_proto_msgTypes,
	}.Build()
	File_microtiezi_proto_tiezi_proto = out.File
	file_microtiezi_proto_tiezi_proto_rawDesc = nil
	file_microtiezi_proto_tiezi_proto_goTypes = nil
	file_microtiezi_proto_tiezi_proto_depIdxs = nil
}
