// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.0
// source: microuser/proto/user.proto

package microuser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Usergetrequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id       int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mail     string `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail,omitempty"`
	Photourl string `protobuf:"bytes,5,opt,name=photourl,proto3" json:"photourl,omitempty"`
}

func (x *Usergetrequest) Reset() {
	*x = Usergetrequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microuser_proto_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Usergetrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usergetrequest) ProtoMessage() {}

func (x *Usergetrequest) ProtoReflect() protoreflect.Message {
	mi := &file_microuser_proto_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usergetrequest.ProtoReflect.Descriptor instead.
func (*Usergetrequest) Descriptor() ([]byte, []int) {
	return file_microuser_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *Usergetrequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Usergetrequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Usergetrequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Usergetrequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *Usergetrequest) GetPhotourl() string {
	if x != nil {
		return x.Photourl
	}
	return ""
}

type Usergetresponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id         int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Password   string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mail       string `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail,omitempty"`
	Photourl   string `protobuf:"bytes,5,opt,name=photourl,proto3" json:"photourl,omitempty"`
	Dianzanshu int64  `protobuf:"varint,6,opt,name=dianzanshu,proto3" json:"dianzanshu,omitempty"`
}

func (x *Usergetresponse) Reset() {
	*x = Usergetresponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microuser_proto_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Usergetresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usergetresponse) ProtoMessage() {}

func (x *Usergetresponse) ProtoReflect() protoreflect.Message {
	mi := &file_microuser_proto_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usergetresponse.ProtoReflect.Descriptor instead.
func (*Usergetresponse) Descriptor() ([]byte, []int) {
	return file_microuser_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *Usergetresponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Usergetresponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Usergetresponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Usergetresponse) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *Usergetresponse) GetPhotourl() string {
	if x != nil {
		return x.Photourl
	}
	return ""
}

func (x *Usergetresponse) GetDianzanshu() int64 {
	if x != nil {
		return x.Dianzanshu
	}
	return 0
}

type Userdenglugetrequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id       int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mail     string `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail,omitempty"`
	Photourl string `protobuf:"bytes,5,opt,name=photourl,proto3" json:"photourl,omitempty"`
}

func (x *Userdenglugetrequest) Reset() {
	*x = Userdenglugetrequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microuser_proto_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Userdenglugetrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Userdenglugetrequest) ProtoMessage() {}

func (x *Userdenglugetrequest) ProtoReflect() protoreflect.Message {
	mi := &file_microuser_proto_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Userdenglugetrequest.ProtoReflect.Descriptor instead.
func (*Userdenglugetrequest) Descriptor() ([]byte, []int) {
	return file_microuser_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *Userdenglugetrequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Userdenglugetrequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Userdenglugetrequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Userdenglugetrequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *Userdenglugetrequest) GetPhotourl() string {
	if x != nil {
		return x.Photourl
	}
	return ""
}

type Userdenglugetresponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id         int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Password   string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mail       string `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail,omitempty"`
	Photourl   string `protobuf:"bytes,5,opt,name=photourl,proto3" json:"photourl,omitempty"`
	Dianzanshu int64  `protobuf:"varint,6,opt,name=dianzanshu,proto3" json:"dianzanshu,omitempty"`
}

func (x *Userdenglugetresponse) Reset() {
	*x = Userdenglugetresponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microuser_proto_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Userdenglugetresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Userdenglugetresponse) ProtoMessage() {}

func (x *Userdenglugetresponse) ProtoReflect() protoreflect.Message {
	mi := &file_microuser_proto_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Userdenglugetresponse.ProtoReflect.Descriptor instead.
func (*Userdenglugetresponse) Descriptor() ([]byte, []int) {
	return file_microuser_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *Userdenglugetresponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Userdenglugetresponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Userdenglugetresponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Userdenglugetresponse) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *Userdenglugetresponse) GetPhotourl() string {
	if x != nil {
		return x.Photourl
	}
	return ""
}

func (x *Userdenglugetresponse) GetDianzanshu() int64 {
	if x != nil {
		return x.Dianzanshu
	}
	return 0
}

type Createequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id       int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mail     string `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail,omitempty"`
	Photourl string `protobuf:"bytes,5,opt,name=photourl,proto3" json:"photourl,omitempty"`
}

func (x *Createequest) Reset() {
	*x = Createequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microuser_proto_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Createequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Createequest) ProtoMessage() {}

func (x *Createequest) ProtoReflect() protoreflect.Message {
	mi := &file_microuser_proto_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Createequest.ProtoReflect.Descriptor instead.
func (*Createequest) Descriptor() ([]byte, []int) {
	return file_microuser_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *Createequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Createequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Createequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Createequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *Createequest) GetPhotourl() string {
	if x != nil {
		return x.Photourl
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag int64 `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"` //是否成功
	Id   int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`     //创建的id
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microuser_proto_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_microuser_proto_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_microuser_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateResponse) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *CreateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Updaterequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id       int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mail     string `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail,omitempty"`
	Photourl string `protobuf:"bytes,5,opt,name=photourl,proto3" json:"photourl,omitempty"`
}

func (x *Updaterequest) Reset() {
	*x = Updaterequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microuser_proto_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Updaterequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Updaterequest) ProtoMessage() {}

func (x *Updaterequest) ProtoReflect() protoreflect.Message {
	mi := &file_microuser_proto_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Updaterequest.ProtoReflect.Descriptor instead.
func (*Updaterequest) Descriptor() ([]byte, []int) {
	return file_microuser_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *Updaterequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Updaterequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Updaterequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Updaterequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *Updaterequest) GetPhotourl() string {
	if x != nil {
		return x.Photourl
	}
	return ""
}

type Updateresponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id       int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mail     string `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail,omitempty"`
	Photourl string `protobuf:"bytes,5,opt,name=photourl,proto3" json:"photourl,omitempty"`
}

func (x *Updateresponse) Reset() {
	*x = Updateresponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microuser_proto_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Updateresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Updateresponse) ProtoMessage() {}

func (x *Updateresponse) ProtoReflect() protoreflect.Message {
	mi := &file_microuser_proto_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Updateresponse.ProtoReflect.Descriptor instead.
func (*Updateresponse) Descriptor() ([]byte, []int) {
	return file_microuser_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *Updateresponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Updateresponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Updateresponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Updateresponse) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *Updateresponse) GetPhotourl() string {
	if x != nil {
		return x.Photourl
	}
	return ""
}

type Userpaihangrequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *Userpaihangrequest) Reset() {
	*x = Userpaihangrequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microuser_proto_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Userpaihangrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Userpaihangrequest) ProtoMessage() {}

func (x *Userpaihangrequest) ProtoReflect() protoreflect.Message {
	mi := &file_microuser_proto_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Userpaihangrequest.ProtoReflect.Descriptor instead.
func (*Userpaihangrequest) Descriptor() ([]byte, []int) {
	return file_microuser_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *Userpaihangrequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type Userpaihangresponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Userpaihangresponse_List `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *Userpaihangresponse) Reset() {
	*x = Userpaihangresponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microuser_proto_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Userpaihangresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Userpaihangresponse) ProtoMessage() {}

func (x *Userpaihangresponse) ProtoReflect() protoreflect.Message {
	mi := &file_microuser_proto_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Userpaihangresponse.ProtoReflect.Descriptor instead.
func (*Userpaihangresponse) Descriptor() ([]byte, []int) {
	return file_microuser_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *Userpaihangresponse) GetList() []*Userpaihangresponse_List {
	if x != nil {
		return x.List
	}
	return nil
}

type Userpaihangresponse_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id         int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Mail       string `protobuf:"bytes,3,opt,name=mail,proto3" json:"mail,omitempty"`
	Photourl   string `protobuf:"bytes,4,opt,name=photourl,proto3" json:"photourl,omitempty"`
	Dianzanshu int64  `protobuf:"varint,5,opt,name=dianzanshu,proto3" json:"dianzanshu,omitempty"`
}

func (x *Userpaihangresponse_List) Reset() {
	*x = Userpaihangresponse_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microuser_proto_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Userpaihangresponse_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Userpaihangresponse_List) ProtoMessage() {}

func (x *Userpaihangresponse_List) ProtoReflect() protoreflect.Message {
	mi := &file_microuser_proto_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Userpaihangresponse_List.ProtoReflect.Descriptor instead.
func (*Userpaihangresponse_List) Descriptor() ([]byte, []int) {
	return file_microuser_proto_user_proto_rawDescGZIP(), []int{9, 0}
}

func (x *Userpaihangresponse_List) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Userpaihangresponse_List) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Userpaihangresponse_List) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *Userpaihangresponse_List) GetPhotourl() string {
	if x != nil {
		return x.Photourl
	}
	return ""
}

func (x *Userpaihangresponse_List) GetDianzanshu() int64 {
	if x != nil {
		return x.Dianzanshu
	}
	return 0
}

var File_microuser_proto_user_proto protoreflect.FileDescriptor

var file_microuser_proto_user_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x22, 0x80, 0x01, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72,
	0x67, 0x65, 0x74, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x22, 0xa1, 0x01, 0x0a, 0x0f, 0x55,
	0x73, 0x65, 0x72, 0x67, 0x65, 0x74, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x73, 0x68, 0x75, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x73, 0x68, 0x75, 0x22, 0x86,
	0x01, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x64, 0x65, 0x6e, 0x67, 0x6c, 0x75, 0x67, 0x65, 0x74,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x22, 0xa7, 0x01, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x72,
	0x64, 0x65, 0x6e, 0x67, 0x6c, 0x75, 0x67, 0x65, 0x74, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72,
	0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x73, 0x68, 0x75, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x73, 0x68,
	0x75, 0x22, 0x7e, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72,
	0x6c, 0x22, 0x34, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x7f, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x22, 0x80, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x22, 0x28, 0x0a, 0x12, 0x55,
	0x73, 0x65, 0x72, 0x70, 0x61, 0x69, 0x68, 0x61, 0x6e, 0x67, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0xca, 0x01, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x70, 0x61,
	0x69, 0x68, 0x61, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x70, 0x61, 0x69, 0x68,
	0x61, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x7a, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75,
	0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75,
	0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x73, 0x68, 0x75,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x73,
	0x68, 0x75, 0x32, 0xec, 0x02, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3e, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x67, 0x65, 0x74, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x67, 0x65, 0x74, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3f, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x07, 0x50, 0x61, 0x69, 0x68, 0x61, 0x6e, 0x67, 0x12, 0x1d,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x70,
	0x61, 0x69, 0x68, 0x61, 0x6e, 0x67, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x70, 0x61,
	0x69, 0x68, 0x61, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x50, 0x0a, 0x09, 0x44, 0x65, 0x6e, 0x67, 0x6c, 0x75, 0x67, 0x65, 0x74, 0x12, 0x1f, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x64, 0x65, 0x6e,
	0x67, 0x6c, 0x75, 0x67, 0x65, 0x74, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x64, 0x65,
	0x6e, 0x67, 0x6c, 0x75, 0x67, 0x65, 0x74, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_microuser_proto_user_proto_rawDescOnce sync.Once
	file_microuser_proto_user_proto_rawDescData = file_microuser_proto_user_proto_rawDesc
)

func file_microuser_proto_user_proto_rawDescGZIP() []byte {
	file_microuser_proto_user_proto_rawDescOnce.Do(func() {
		file_microuser_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_microuser_proto_user_proto_rawDescData)
	})
	return file_microuser_proto_user_proto_rawDescData
}

var file_microuser_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_microuser_proto_user_proto_goTypes = []interface{}{
	(*Usergetrequest)(nil),           // 0: microuser.Usergetrequest
	(*Usergetresponse)(nil),          // 1: microuser.Usergetresponse
	(*Userdenglugetrequest)(nil),     // 2: microuser.Userdenglugetrequest
	(*Userdenglugetresponse)(nil),    // 3: microuser.Userdenglugetresponse
	(*Createequest)(nil),             // 4: microuser.Createequest
	(*CreateResponse)(nil),           // 5: microuser.CreateResponse
	(*Updaterequest)(nil),            // 6: microuser.Updaterequest
	(*Updateresponse)(nil),           // 7: microuser.Updateresponse
	(*Userpaihangrequest)(nil),       // 8: microuser.Userpaihangrequest
	(*Userpaihangresponse)(nil),      // 9: microuser.Userpaihangresponse
	(*Userpaihangresponse_List)(nil), // 10: microuser.Userpaihangresponse.List
}
var file_microuser_proto_user_proto_depIdxs = []int32{
	10, // 0: microuser.Userpaihangresponse.list:type_name -> microuser.Userpaihangresponse.List
	4,  // 1: microuser.UserService.Create:input_type -> microuser.Createequest
	0,  // 2: microuser.UserService.Get:input_type -> microuser.Usergetrequest
	6,  // 3: microuser.UserService.Update:input_type -> microuser.Updaterequest
	8,  // 4: microuser.UserService.Paihang:input_type -> microuser.Userpaihangrequest
	2,  // 5: microuser.UserService.Dengluget:input_type -> microuser.Userdenglugetrequest
	5,  // 6: microuser.UserService.Create:output_type -> microuser.CreateResponse
	1,  // 7: microuser.UserService.Get:output_type -> microuser.Usergetresponse
	7,  // 8: microuser.UserService.Update:output_type -> microuser.Updateresponse
	9,  // 9: microuser.UserService.Paihang:output_type -> microuser.Userpaihangresponse
	3,  // 10: microuser.UserService.Dengluget:output_type -> microuser.Userdenglugetresponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_microuser_proto_user_proto_init() }
func file_microuser_proto_user_proto_init() {
	if File_microuser_proto_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_microuser_proto_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Usergetrequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microuser_proto_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Usergetresponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microuser_proto_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Userdenglugetrequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microuser_proto_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Userdenglugetresponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microuser_proto_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Createequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microuser_proto_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microuser_proto_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Updaterequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microuser_proto_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Updateresponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microuser_proto_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Userpaihangrequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microuser_proto_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Userpaihangresponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microuser_proto_user_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Userpaihangresponse_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_microuser_proto_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_microuser_proto_user_proto_goTypes,
		DependencyIndexes: file_microuser_proto_user_proto_depIdxs,
		MessageInfos:      file_microuser_proto_user_proto_msgTypes,
	}.Build()
	File_microuser_proto_user_proto = out.File
	file_microuser_proto_user_proto_rawDesc = nil
	file_microuser_proto_user_proto_goTypes = nil
	file_microuser_proto_user_proto_depIdxs = nil
}
