// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.0
// source: microdianzan/proto/dianzan.proto

package microdianzan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dianzangetrequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Followid int64 `protobuf:"varint,2,opt,name=followid,proto3" json:"followid,omitempty"`
	Postid   int64 `protobuf:"varint,4,opt,name=postid,proto3" json:"postid,omitempty"`
}

func (x *Dianzangetrequest) Reset() {
	*x = Dianzangetrequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microdianzan_proto_dianzan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dianzangetrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dianzangetrequest) ProtoMessage() {}

func (x *Dianzangetrequest) ProtoReflect() protoreflect.Message {
	mi := &file_microdianzan_proto_dianzan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dianzangetrequest.ProtoReflect.Descriptor instead.
func (*Dianzangetrequest) Descriptor() ([]byte, []int) {
	return file_microdianzan_proto_dianzan_proto_rawDescGZIP(), []int{0}
}

func (x *Dianzangetrequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Dianzangetrequest) GetFollowid() int64 {
	if x != nil {
		return x.Followid
	}
	return 0
}

func (x *Dianzangetrequest) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

type Dianzangetresponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Followid int64 `protobuf:"varint,2,opt,name=followid,proto3" json:"followid,omitempty"`
	Id       int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Postid   int64 `protobuf:"varint,4,opt,name=postid,proto3" json:"postid,omitempty"`
	Flag     int64 `protobuf:"varint,5,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *Dianzangetresponse) Reset() {
	*x = Dianzangetresponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microdianzan_proto_dianzan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dianzangetresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dianzangetresponse) ProtoMessage() {}

func (x *Dianzangetresponse) ProtoReflect() protoreflect.Message {
	mi := &file_microdianzan_proto_dianzan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dianzangetresponse.ProtoReflect.Descriptor instead.
func (*Dianzangetresponse) Descriptor() ([]byte, []int) {
	return file_microdianzan_proto_dianzan_proto_rawDescGZIP(), []int{1}
}

func (x *Dianzangetresponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Dianzangetresponse) GetFollowid() int64 {
	if x != nil {
		return x.Followid
	}
	return 0
}

func (x *Dianzangetresponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dianzangetresponse) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

func (x *Dianzangetresponse) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type Createequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Followid int64 `protobuf:"varint,2,opt,name=followid,proto3" json:"followid,omitempty"`
	Postid   int64 `protobuf:"varint,4,opt,name=postid,proto3" json:"postid,omitempty"`
}

func (x *Createequest) Reset() {
	*x = Createequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microdianzan_proto_dianzan_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Createequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Createequest) ProtoMessage() {}

func (x *Createequest) ProtoReflect() protoreflect.Message {
	mi := &file_microdianzan_proto_dianzan_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Createequest.ProtoReflect.Descriptor instead.
func (*Createequest) Descriptor() ([]byte, []int) {
	return file_microdianzan_proto_dianzan_proto_rawDescGZIP(), []int{2}
}

func (x *Createequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Createequest) GetFollowid() int64 {
	if x != nil {
		return x.Followid
	}
	return 0
}

func (x *Createequest) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag int64 `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"` //是否成功
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microdianzan_proto_dianzan_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_microdianzan_proto_dianzan_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_microdianzan_proto_dianzan_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResponse) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type Dianzandeletrequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Dianzandeletrequest) Reset() {
	*x = Dianzandeletrequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microdianzan_proto_dianzan_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dianzandeletrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dianzandeletrequest) ProtoMessage() {}

func (x *Dianzandeletrequest) ProtoReflect() protoreflect.Message {
	mi := &file_microdianzan_proto_dianzan_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dianzandeletrequest.ProtoReflect.Descriptor instead.
func (*Dianzandeletrequest) Descriptor() ([]byte, []int) {
	return file_microdianzan_proto_dianzan_proto_rawDescGZIP(), []int{4}
}

func (x *Dianzandeletrequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Dianzandeleteresponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag int64 `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *Dianzandeleteresponse) Reset() {
	*x = Dianzandeleteresponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microdianzan_proto_dianzan_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dianzandeleteresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dianzandeleteresponse) ProtoMessage() {}

func (x *Dianzandeleteresponse) ProtoReflect() protoreflect.Message {
	mi := &file_microdianzan_proto_dianzan_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dianzandeleteresponse.ProtoReflect.Descriptor instead.
func (*Dianzandeleteresponse) Descriptor() ([]byte, []int) {
	return file_microdianzan_proto_dianzan_proto_rawDescGZIP(), []int{5}
}

func (x *Dianzandeleteresponse) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type DianzanReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Followid int64 `protobuf:"varint,2,opt,name=followid,proto3" json:"followid,omitempty"`
	Id       int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Postid   int64 `protobuf:"varint,4,opt,name=postid,proto3" json:"postid,omitempty"`
}

func (x *DianzanReq) Reset() {
	*x = DianzanReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microdianzan_proto_dianzan_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DianzanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DianzanReq) ProtoMessage() {}

func (x *DianzanReq) ProtoReflect() protoreflect.Message {
	mi := &file_microdianzan_proto_dianzan_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DianzanReq.ProtoReflect.Descriptor instead.
func (*DianzanReq) Descriptor() ([]byte, []int) {
	return file_microdianzan_proto_dianzan_proto_rawDescGZIP(), []int{6}
}

func (x *DianzanReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DianzanReq) GetFollowid() int64 {
	if x != nil {
		return x.Followid
	}
	return 0
}

func (x *DianzanReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DianzanReq) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

type DianzanRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Followid int64 `protobuf:"varint,2,opt,name=followid,proto3" json:"followid,omitempty"`
	Id       int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Postid   int64 `protobuf:"varint,4,opt,name=postid,proto3" json:"postid,omitempty"`
	Flag     int64 `protobuf:"varint,5,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *DianzanRsp) Reset() {
	*x = DianzanRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microdianzan_proto_dianzan_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DianzanRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DianzanRsp) ProtoMessage() {}

func (x *DianzanRsp) ProtoReflect() protoreflect.Message {
	mi := &file_microdianzan_proto_dianzan_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DianzanRsp.ProtoReflect.Descriptor instead.
func (*DianzanRsp) Descriptor() ([]byte, []int) {
	return file_microdianzan_proto_dianzan_proto_rawDescGZIP(), []int{7}
}

func (x *DianzanRsp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DianzanRsp) GetFollowid() int64 {
	if x != nil {
		return x.Followid
	}
	return 0
}

func (x *DianzanRsp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DianzanRsp) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

func (x *DianzanRsp) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

var File_microdianzan_proto_dianzan_proto protoreflect.FileDescriptor

var file_microdianzan_proto_dianzan_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e,
	0x22, 0x59, 0x0a, 0x11, 0x44, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x67, 0x65, 0x74, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x22, 0x7e, 0x0a, 0x12, 0x44,
	0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x67, 0x65, 0x74, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x54, 0x0a, 0x0c, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73,
	0x74, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69,
	0x64, 0x22, 0x24, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x69, 0x61, 0x6e, 0x7a,
	0x61, 0x6e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2b,
	0x0a, 0x15, 0x44, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x62, 0x0a, 0x0a, 0x44,
	0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x22,
	0x76, 0x0a, 0x0a, 0x44, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x6f, 0x73, 0x74, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x73,
	0x74, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x32, 0xb7, 0x02, 0x0a, 0x0e, 0x44, 0x69, 0x61, 0x6e,
	0x7a, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x06, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x64, 0x69, 0x61, 0x6e,
	0x7a, 0x61, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4a, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x64,
	0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x2e, 0x44, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x67, 0x65,
	0x74, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x2e, 0x44, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x67,
	0x65, 0x74, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x64, 0x69,
	0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x2e, 0x44, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x2e, 0x44, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3f, 0x0a, 0x07, 0x44, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x12, 0x18, 0x2e, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x2e, 0x44, 0x69, 0x61, 0x6e, 0x7a,
	0x61, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x64, 0x69, 0x61,
	0x6e, 0x7a, 0x61, 0x6e, 0x2e, 0x44, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x52, 0x73, 0x70, 0x22,
	0x00, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x64, 0x69, 0x61, 0x6e, 0x7a, 0x61, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_microdianzan_proto_dianzan_proto_rawDescOnce sync.Once
	file_microdianzan_proto_dianzan_proto_rawDescData = file_microdianzan_proto_dianzan_proto_rawDesc
)

func file_microdianzan_proto_dianzan_proto_rawDescGZIP() []byte {
	file_microdianzan_proto_dianzan_proto_rawDescOnce.Do(func() {
		file_microdianzan_proto_dianzan_proto_rawDescData = protoimpl.X.CompressGZIP(file_microdianzan_proto_dianzan_proto_rawDescData)
	})
	return file_microdianzan_proto_dianzan_proto_rawDescData
}

var file_microdianzan_proto_dianzan_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_microdianzan_proto_dianzan_proto_goTypes = []interface{}{
	(*Dianzangetrequest)(nil),     // 0: microdianzan.Dianzangetrequest
	(*Dianzangetresponse)(nil),    // 1: microdianzan.Dianzangetresponse
	(*Createequest)(nil),          // 2: microdianzan.Createequest
	(*CreateResponse)(nil),        // 3: microdianzan.CreateResponse
	(*Dianzandeletrequest)(nil),   // 4: microdianzan.Dianzandeletrequest
	(*Dianzandeleteresponse)(nil), // 5: microdianzan.Dianzandeleteresponse
	(*DianzanReq)(nil),            // 6: microdianzan.DianzanReq
	(*DianzanRsp)(nil),            // 7: microdianzan.DianzanRsp
}
var file_microdianzan_proto_dianzan_proto_depIdxs = []int32{
	2, // 0: microdianzan.DianzanService.Create:input_type -> microdianzan.Createequest
	0, // 1: microdianzan.DianzanService.Get:input_type -> microdianzan.Dianzangetrequest
	4, // 2: microdianzan.DianzanService.Delete:input_type -> microdianzan.Dianzandeletrequest
	6, // 3: microdianzan.DianzanService.Dianzan:input_type -> microdianzan.DianzanReq
	3, // 4: microdianzan.DianzanService.Create:output_type -> microdianzan.CreateResponse
	1, // 5: microdianzan.DianzanService.Get:output_type -> microdianzan.Dianzangetresponse
	5, // 6: microdianzan.DianzanService.Delete:output_type -> microdianzan.Dianzandeleteresponse
	7, // 7: microdianzan.DianzanService.Dianzan:output_type -> microdianzan.DianzanRsp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_microdianzan_proto_dianzan_proto_init() }
func file_microdianzan_proto_dianzan_proto_init() {
	if File_microdianzan_proto_dianzan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_microdianzan_proto_dianzan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dianzangetrequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microdianzan_proto_dianzan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dianzangetresponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microdianzan_proto_dianzan_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Createequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microdianzan_proto_dianzan_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microdianzan_proto_dianzan_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dianzandeletrequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microdianzan_proto_dianzan_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dianzandeleteresponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microdianzan_proto_dianzan_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DianzanReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microdianzan_proto_dianzan_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DianzanRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_microdianzan_proto_dianzan_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_microdianzan_proto_dianzan_proto_goTypes,
		DependencyIndexes: file_microdianzan_proto_dianzan_proto_depIdxs,
		MessageInfos:      file_microdianzan_proto_dianzan_proto_msgTypes,
	}.Build()
	File_microdianzan_proto_dianzan_proto = out.File
	file_microdianzan_proto_dianzan_proto_rawDesc = nil
	file_microdianzan_proto_dianzan_proto_goTypes = nil
	file_microdianzan_proto_dianzan_proto_depIdxs = nil
}
