// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.0
// source: microguanzhu/proto/guanzhu.proto

package microguanzhu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Guanzhugetrequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Followid int64 `protobuf:"varint,2,opt,name=followid,proto3" json:"followid,omitempty"`
}

func (x *Guanzhugetrequest) Reset() {
	*x = Guanzhugetrequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Guanzhugetrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guanzhugetrequest) ProtoMessage() {}

func (x *Guanzhugetrequest) ProtoReflect() protoreflect.Message {
	mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guanzhugetrequest.ProtoReflect.Descriptor instead.
func (*Guanzhugetrequest) Descriptor() ([]byte, []int) {
	return file_microguanzhu_proto_guanzhu_proto_rawDescGZIP(), []int{0}
}

func (x *Guanzhugetrequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Guanzhugetrequest) GetFollowid() int64 {
	if x != nil {
		return x.Followid
	}
	return 0
}

type Guanzhugetresponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Followid int64 `protobuf:"varint,2,opt,name=followid,proto3" json:"followid,omitempty"`
	Id       int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Status   int64 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Flag     int64 `protobuf:"varint,5,opt,name=flag,proto3" json:"flag,omitempty"` //1为有记录 2为无记录
}

func (x *Guanzhugetresponse) Reset() {
	*x = Guanzhugetresponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Guanzhugetresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guanzhugetresponse) ProtoMessage() {}

func (x *Guanzhugetresponse) ProtoReflect() protoreflect.Message {
	mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guanzhugetresponse.ProtoReflect.Descriptor instead.
func (*Guanzhugetresponse) Descriptor() ([]byte, []int) {
	return file_microguanzhu_proto_guanzhu_proto_rawDescGZIP(), []int{1}
}

func (x *Guanzhugetresponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Guanzhugetresponse) GetFollowid() int64 {
	if x != nil {
		return x.Followid
	}
	return 0
}

func (x *Guanzhugetresponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Guanzhugetresponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Guanzhugetresponse) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type Createequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Followid int64 `protobuf:"varint,2,opt,name=followid,proto3" json:"followid,omitempty"`
	Status   int64 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Createequest) Reset() {
	*x = Createequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Createequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Createequest) ProtoMessage() {}

func (x *Createequest) ProtoReflect() protoreflect.Message {
	mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Createequest.ProtoReflect.Descriptor instead.
func (*Createequest) Descriptor() ([]byte, []int) {
	return file_microguanzhu_proto_guanzhu_proto_rawDescGZIP(), []int{2}
}

func (x *Createequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Createequest) GetFollowid() int64 {
	if x != nil {
		return x.Followid
	}
	return 0
}

func (x *Createequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag int64 `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"` //是否成功
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_microguanzhu_proto_guanzhu_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResponse) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type Guanzhulistrequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Page int64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *Guanzhulistrequest) Reset() {
	*x = Guanzhulistrequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Guanzhulistrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guanzhulistrequest) ProtoMessage() {}

func (x *Guanzhulistrequest) ProtoReflect() protoreflect.Message {
	mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guanzhulistrequest.ProtoReflect.Descriptor instead.
func (*Guanzhulistrequest) Descriptor() ([]byte, []int) {
	return file_microguanzhu_proto_guanzhu_proto_rawDescGZIP(), []int{4}
}

func (x *Guanzhulistrequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Guanzhulistrequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type Guanzhulistresponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Guanzhulistresponse_List `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *Guanzhulistresponse) Reset() {
	*x = Guanzhulistresponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Guanzhulistresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guanzhulistresponse) ProtoMessage() {}

func (x *Guanzhulistresponse) ProtoReflect() protoreflect.Message {
	mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guanzhulistresponse.ProtoReflect.Descriptor instead.
func (*Guanzhulistresponse) Descriptor() ([]byte, []int) {
	return file_microguanzhu_proto_guanzhu_proto_rawDescGZIP(), []int{5}
}

func (x *Guanzhulistresponse) GetList() []*Guanzhulistresponse_List {
	if x != nil {
		return x.List
	}
	return nil
}

type Guanzhudeletrequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Followid int64 `protobuf:"varint,2,opt,name=followid,proto3" json:"followid,omitempty"`
}

func (x *Guanzhudeletrequest) Reset() {
	*x = Guanzhudeletrequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Guanzhudeletrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guanzhudeletrequest) ProtoMessage() {}

func (x *Guanzhudeletrequest) ProtoReflect() protoreflect.Message {
	mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guanzhudeletrequest.ProtoReflect.Descriptor instead.
func (*Guanzhudeletrequest) Descriptor() ([]byte, []int) {
	return file_microguanzhu_proto_guanzhu_proto_rawDescGZIP(), []int{6}
}

func (x *Guanzhudeletrequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Guanzhudeletrequest) GetFollowid() int64 {
	if x != nil {
		return x.Followid
	}
	return 0
}

type Guanzhudeleteresponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag int64 `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *Guanzhudeleteresponse) Reset() {
	*x = Guanzhudeleteresponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Guanzhudeleteresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guanzhudeleteresponse) ProtoMessage() {}

func (x *Guanzhudeleteresponse) ProtoReflect() protoreflect.Message {
	mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guanzhudeleteresponse.ProtoReflect.Descriptor instead.
func (*Guanzhudeleteresponse) Descriptor() ([]byte, []int) {
	return file_microguanzhu_proto_guanzhu_proto_rawDescGZIP(), []int{7}
}

func (x *Guanzhudeleteresponse) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type Guanzhulistresponse_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Followid int64 `protobuf:"varint,2,opt,name=followid,proto3" json:"followid,omitempty"`
	Id       int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Status   int64 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Guanzhulistresponse_List) Reset() {
	*x = Guanzhulistresponse_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Guanzhulistresponse_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guanzhulistresponse_List) ProtoMessage() {}

func (x *Guanzhulistresponse_List) ProtoReflect() protoreflect.Message {
	mi := &file_microguanzhu_proto_guanzhu_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guanzhulistresponse_List.ProtoReflect.Descriptor instead.
func (*Guanzhulistresponse_List) Descriptor() ([]byte, []int) {
	return file_microguanzhu_proto_guanzhu_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Guanzhulistresponse_List) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Guanzhulistresponse_List) GetFollowid() int64 {
	if x != nil {
		return x.Followid
	}
	return 0
}

func (x *Guanzhulistresponse_List) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Guanzhulistresponse_List) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_microguanzhu_proto_guanzhu_proto protoreflect.FileDescriptor

var file_microguanzhu_proto_guanzhu_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x67, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x67, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75,
	0x22, 0x41, 0x0a, 0x11, 0x47, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x67, 0x65, 0x74, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x69, 0x64, 0x22, 0x7e, 0x0a, 0x12, 0x47, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x67, 0x65,
	0x74, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66,
	0x6c, 0x61, 0x67, 0x22, 0x54, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x24, 0x0a, 0x0e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22,
	0x3a, 0x0a, 0x12, 0x47, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x6c, 0x69, 0x73, 0x74, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0xaf, 0x01, 0x0a, 0x13,
	0x47, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x6c, 0x69, 0x73, 0x74, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x67, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75,
	0x2e, 0x47, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x6c, 0x69, 0x73, 0x74, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a,
	0x5c, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x43, 0x0a,
	0x13, 0x47, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x69, 0x64, 0x22, 0x2b, 0x0a, 0x15, 0x47, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x32,
	0xc5, 0x02, 0x0a, 0x0e, 0x47, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x44, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x67, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x67, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12,
	0x1f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x67, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x2e, 0x47,
	0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x67, 0x65, 0x74, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x67, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x2e,
	0x47, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x67, 0x65, 0x74, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x21,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x67, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x2e, 0x47, 0x75,
	0x61, 0x6e, 0x7a, 0x68, 0x75, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x67, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75,
	0x2e, 0x47, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x20, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x67, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x2e,
	0x47, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x6c, 0x69, 0x73, 0x74, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x67, 0x75, 0x61, 0x6e, 0x7a, 0x68,
	0x75, 0x2e, 0x47, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x6c, 0x69, 0x73, 0x74, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x67, 0x75, 0x61, 0x6e, 0x7a, 0x68, 0x75, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_microguanzhu_proto_guanzhu_proto_rawDescOnce sync.Once
	file_microguanzhu_proto_guanzhu_proto_rawDescData = file_microguanzhu_proto_guanzhu_proto_rawDesc
)

func file_microguanzhu_proto_guanzhu_proto_rawDescGZIP() []byte {
	file_microguanzhu_proto_guanzhu_proto_rawDescOnce.Do(func() {
		file_microguanzhu_proto_guanzhu_proto_rawDescData = protoimpl.X.CompressGZIP(file_microguanzhu_proto_guanzhu_proto_rawDescData)
	})
	return file_microguanzhu_proto_guanzhu_proto_rawDescData
}

var file_microguanzhu_proto_guanzhu_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_microguanzhu_proto_guanzhu_proto_goTypes = []interface{}{
	(*Guanzhugetrequest)(nil),        // 0: microguanzhu.Guanzhugetrequest
	(*Guanzhugetresponse)(nil),       // 1: microguanzhu.Guanzhugetresponse
	(*Createequest)(nil),             // 2: microguanzhu.Createequest
	(*CreateResponse)(nil),           // 3: microguanzhu.CreateResponse
	(*Guanzhulistrequest)(nil),       // 4: microguanzhu.Guanzhulistrequest
	(*Guanzhulistresponse)(nil),      // 5: microguanzhu.Guanzhulistresponse
	(*Guanzhudeletrequest)(nil),      // 6: microguanzhu.Guanzhudeletrequest
	(*Guanzhudeleteresponse)(nil),    // 7: microguanzhu.Guanzhudeleteresponse
	(*Guanzhulistresponse_List)(nil), // 8: microguanzhu.Guanzhulistresponse.List
}
var file_microguanzhu_proto_guanzhu_proto_depIdxs = []int32{
	8, // 0: microguanzhu.Guanzhulistresponse.list:type_name -> microguanzhu.Guanzhulistresponse.List
	2, // 1: microguanzhu.GuanzhuService.Create:input_type -> microguanzhu.Createequest
	0, // 2: microguanzhu.GuanzhuService.Get:input_type -> microguanzhu.Guanzhugetrequest
	6, // 3: microguanzhu.GuanzhuService.Delete:input_type -> microguanzhu.Guanzhudeletrequest
	4, // 4: microguanzhu.GuanzhuService.List:input_type -> microguanzhu.Guanzhulistrequest
	3, // 5: microguanzhu.GuanzhuService.Create:output_type -> microguanzhu.CreateResponse
	1, // 6: microguanzhu.GuanzhuService.Get:output_type -> microguanzhu.Guanzhugetresponse
	7, // 7: microguanzhu.GuanzhuService.Delete:output_type -> microguanzhu.Guanzhudeleteresponse
	5, // 8: microguanzhu.GuanzhuService.List:output_type -> microguanzhu.Guanzhulistresponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_microguanzhu_proto_guanzhu_proto_init() }
func file_microguanzhu_proto_guanzhu_proto_init() {
	if File_microguanzhu_proto_guanzhu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_microguanzhu_proto_guanzhu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Guanzhugetrequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microguanzhu_proto_guanzhu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Guanzhugetresponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microguanzhu_proto_guanzhu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Createequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microguanzhu_proto_guanzhu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microguanzhu_proto_guanzhu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Guanzhulistrequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microguanzhu_proto_guanzhu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Guanzhulistresponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microguanzhu_proto_guanzhu_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Guanzhudeletrequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microguanzhu_proto_guanzhu_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Guanzhudeleteresponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microguanzhu_proto_guanzhu_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Guanzhulistresponse_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_microguanzhu_proto_guanzhu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_microguanzhu_proto_guanzhu_proto_goTypes,
		DependencyIndexes: file_microguanzhu_proto_guanzhu_proto_depIdxs,
		MessageInfos:      file_microguanzhu_proto_guanzhu_proto_msgTypes,
	}.Build()
	File_microguanzhu_proto_guanzhu_proto = out.File
	file_microguanzhu_proto_guanzhu_proto_rawDesc = nil
	file_microguanzhu_proto_guanzhu_proto_goTypes = nil
	file_microguanzhu_proto_guanzhu_proto_depIdxs = nil
}
